### ISSUE TITLE
Patch tool does not work on floaty wavs

### ISSUE THREAD

**Issue by ch3pjw** [foolswood/adifflib#18]
The `patch_frames` code doesn't handle float-based wav data at all well! When applying a patch, I get a resulting file of the right length, but most of the data is zeros, with the very occaisonaly spike to 1.0. I'm presuming this is a scaling issue or similar - as we've seen before.

**Comment by foolswood** [comment]
The (not terribly well tested yet) sample_reader_select branch shows what I mean.

**Comment by foolswood** [comment]
I believe pull request #21 (now merged) fixed this issue.

Patching does need tests though.
