### ISSUE TITLE
Hunk start and end points are aligned to chunk boundaries

### ISSUE THREAD

**Issue by foolswood** [foolswood/adifflib#25]
This is an artifact of the chunk by chunk diff we currently have.

The easiest way to see this is that at the start of an insertion there will often be a false 'change' shown by the diff since the inserted section is unlikely to have started exactly at a chunk boundary.

This will involve a second stage of diffing (once we have the rough hunks) to find the exact start and end points.

**Comment by foolswood** [comment]
Before work starts on this I would like to see the adiff tests (#23) merged to avoid conflicts in the tests.

**Comment by ch3pjw** [comment]
#23 now merged :-)

**Comment by foolswood** [comment]
This is sorted, we're not quite sample perfect, but we aren't stuck on chunk boundaries since #39.
