### ISSUE TITLE
adiff `files_identical` test appears racy

### ISSUE THREAD

**Issue by ch3pjw** [foolswood/adifflib#37]
Running `make check` repeatedly occaisionally shows a failure:
```
/adiff/double: **
ERROR:tests/unittest_adiff.c:232:files_identical: assertion failed (i < i): (60 < 60)
```

**Comment by ch3pjw** [comment]
Erm, digging into the tests, I see that that error is not necessarily that specific :-(

**Comment by ch3pjw** [comment]
Got it to fail on `/adiff/float` too. Am testing just by running:
`$ while make check; do :; done;`

**Comment by foolswood** [comment]
Gah, I was hoping to avoid such things by being in a single synchronous thread.

Have started looking for the issue, nothing is jumping out yet, the files created look to be the same in both the success and failure case (with the exception of the patch which is wrong).

**Comment by foolswood** [comment]
Looks to always and only be at byte 60, so I'm looking into the possibility that it is related to wav headers.

**Comment by foolswood** [comment]
It is in the RIFF headers, specifically the PEAK chunk [1], not the data section so the patch has worked fine.

original:
`(ommitted first 47 bytes)
id: 120 105 101 113 (PEAK)
length: 020 000 000 000
data:
 version: 001 000 000 000
 timestamp: 007 016 337 124
            ^ byte 60
(ommitted rest of file)`

patched:
`(ommitted first 47 bytes)
id: 120 105 101 113 (PEAK)
length: 020 000 000 000
data:
 version: 001 000 000 000
 timestamp: 010 016 337 124
            ^ byte 60
(ommitted rest of file)`

The timestamp is that of file creation to 1 second precision, so I'm not entirely sure how to go about fixing this reliably without parsing the riff headers in the test (although they aren't that complicated so maybe we'll have to do that).

[1] https://web.archive.org/web/20060501212456/http://shoko.calarts.edu/~tre/PeakChunk.html

**Comment by foolswood** [comment]
Also to reproduce faster you can use `while ./unittest_adiff; do echo 'passed'; done`.

**Comment by ch3pjw** [comment]
Fab!
