### ISSUE TITLE
Insertions in data that is the same either side contain some commonality in the diff

### ISSUE THREAD

**Issue by foolswood** [foolswood/adifflib#40]
Such insertions currently contain a bit of the common data, which is then counteracted by the next chunk (or end of file) containing a corresponding deletion.

This is an artifact of the chunk based diffing algorithm used.
It would be good if this didn't happen as it is semantically a bit weird.

**Comment by foolswood** [comment]
I believe this is covered by #42.

**Comment by ch3pjw** [comment]
I concur :-)
